In [18]:
import pandas as pd

In [19]:
Kidney_disease = pd.read_csv("D:\Data for Preprocessing\kidney_disease.csv")

In [20]:
Kidney_disease

,age,Blood Pressure,Specific Gravity,Albumin,Sugar,Red Blood Cells,Pus Cell,Pus Cell Clumps,Bacteria,Blood Glucose random,...,Packed Cell Volume,White Blood Cell Count,Red blood cell count,Hypertension,Diabetes Mellitus,Coronary Artery Disease,Appetite,Pedal Edma,Anemia,classification
0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,140.0,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,75.0,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,100.0,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,114.0,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,131.0,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [21]:
Kidney_disease['Packed Cell Volume'] = pd.to_numeric(Kidney_disease['Packed Cell Volume'], errors='coerce')
Kidney_disease['White Blood Cell Count'] = pd.to_numeric(Kidney_disease['White Blood Cell Count'], errors='coerce')
Kidney_disease['Red blood cell count'] = pd.to_numeric(Kidney_disease['Red blood cell count'], errors='coerce')

# Now converting to float64
Kidney_disease = Kidney_disease.astype({'Packed Cell Volume': 'float64', 'White Blood Cell Count': 'float64', 'Red blood cell count': 'float64'})

In [22]:
Kidney_disease.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      391 non-null    float64
 1   Blood Pressure           388 non-null    float64
 2   Specific Gravity         353 non-null    float64
 3   Albumin                  354 non-null    float64
 4   Sugar                    351 non-null    float64
 5   Red Blood Cells          248 non-null    object
 6   Pus Cell                 335 non-null    object
 7    Pus Cell Clumps         396 non-null    object
 8   Bacteria                 396 non-null    object
 9   Blood Glucose random     356 non-null    float64
 10  Blood Urea               381 non-null    float64
 11  Serum Creatinine         383 non-null    float64
 12  Sodium                   313 non-null    float64
 13  Potassium                312 non-null    float64
 14  Haemoglobin              348 non-null    float64
 15  Packed Cell Volume       329 non-null    float64
 16  White Blood Cell Count   294 non-null    float64
 17  Red blood cell count     269 non-null    float64
 18  Hypertension             398 non-null    object
 19  Diabetes Mellitus        398 non-null    object
 20  Coronary Artery Disease  398 non-null    object
 21  Appetite                 399 non-null    object
 22  Pedal Edma               399 non-null    object
 23  Anemia                   399 non-null    object
 24  classification           400 non-null    object
dtypes: float64(14), object(11)
memory usage: 78.2+ KB

In [23]:
Numerical_value = Kidney_disease.select_dtypes(include='float64')

In [24]:
Numerical_value

,age,Blood Pressure,Specific Gravity,Albumin,Sugar,Blood Glucose random,Blood Urea,Serum Creatinine,Sodium,Potassium,Haemoglobin,Packed Cell Volume,White Blood Cell Count,Red blood cell count
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,NaN,NaN,15.4,44.0,7800.0,5.2
1,7.0,50.0,1.020,4.0,0.0,NaN,18.0,0.8,NaN,NaN,11.3,38.0,6000.0,NaN
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,NaN,NaN,9.6,31.0,7500.0,NaN
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,NaN,NaN,11.6,35.0,7300.0,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,4.9,15.7,47.0,6700.0,4.9
396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,3.5,16.5,54.0,7800.0,6.2
397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,4.4,15.8,49.0,6600.0,5.4
398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,4.9,14.2,51.0,7200.0,5.9
399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,3.5,15.8,53.0,6800.0,6.1

In [25]:
Categorical_value = Kidney_disease.select_dtypes(include='object')

In [26]:
Categorical_value

,Red Blood Cells,Pus Cell,Pus Cell Clumps,Bacteria,Hypertension,Diabetes Mellitus,Coronary Artery Disease,Appetite,Pedal Edma,Anemia,classification
0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
1,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
396,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
397,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
398,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
399,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd

python
from sklearn.impute import KNNImputer
import numpy as np

# Your data with missing values
data_with_missing = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])

# Create KNN imputer
knn_imputer = KNNImputer(n_neighbors=2)

# Impute missing values
data_imputed = knn_imputer.fit_transform(data_with_missing)

print(data_imputed)


Adjust the parameters according to your specific needs, such as the number of neighbors (`n_neighbors`). This is a basic example, and you might need to adapt it based on your dataset and requirements.

In [27]:
from sklearn.impute import KNNImputer

In [28]:
# Create KNN Imputer
knn_imputer = KNNImputer(n_neighbors=2, weights = 'uniform', metric= 'nan_euclidean')

In [29]:
KNN_Imputed = pd.DataFrame(knn_imputer.fit_transform(Numerical_value))

In [32]:
KNN_Imputed.columns = Numerical_value.columns

In [33]:
KNN_Imputed

,age,Blood Pressure,Specific Gravity,Albumin,Sugar,Blood Glucose random,Blood Urea,Serum Creatinine,Sodium,Potassium,Haemoglobin,Packed Cell Volume,White Blood Cell Count,Red blood cell count
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,139.0,4.45,15.4,44.0,7800.0,5.2
1,7.0,50.0,1.020,4.0,0.0,101.5,18.0,0.8,138.0,3.80,11.3,38.0,6000.0,5.5
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,132.0,4.05,9.6,31.0,7500.0,3.2
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.50,11.2,32.0,6700.0,3.9
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,137.0,4.30,11.6,35.0,7300.0,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,4.90,15.7,47.0,6700.0,4.9
396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,3.50,16.5,54.0,7800.0,6.2
397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,4.40,15.8,49.0,6600.0,5.4
398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,4.90,14.2,51.0,7200.0,5.9
399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,3.50,15.8,53.0,6800.0,6.1

In [37]:
  for i in range(1,5): 
    knn_imputer = KNNImputer(n_neighbors=i, weights = 'uniform', metric= 'nan_euclidean')
    KNN_Imputed = pd.DataFrame(knn_imputer.fit_transform(Numerical_value))
    KNN_Imputed.columns = Numerical_value.columns
  
   # Print or return the imputed DataFrame
    print(f"Imputed values with {i} neighbors:")
    print(KNN_Imputed)
    print("\n")

Imputed values with 1 neighbors:
      age  Blood Pressure  Specific Gravity  Albumin  Sugar  \
0    48.0            80.0             1.020      1.0    0.0
1     7.0            50.0             1.020      4.0    0.0
2    62.0            80.0             1.010      2.0    3.0
3    48.0            70.0             1.005      4.0    0.0
4    51.0            80.0             1.010      2.0    0.0
..    ...             ...               ...      ...    ...
395  55.0            80.0             1.020      0.0    0.0
396  42.0            70.0             1.025      0.0    0.0
397  12.0            80.0             1.020      0.0    0.0
398  17.0            60.0             1.025      0.0    0.0
399  58.0            80.0             1.025      0.0    0.0

     Blood Glucose random  Blood Urea  Serum Creatinine  Sodium  Potassium  \
0                   121.0        36.0               1.2   135.0        3.9
1                    99.0        18.0               0.8   138.0        3.2
2                   423.0        53.0               1.8   132.0        4.0
3                   117.0        56.0               3.8   111.0        2.5
4                   106.0        26.0               1.4   139.0        4.7
..                    ...         ...               ...     ...        ...
395                 140.0        49.0               0.5   150.0        4.9
396                  75.0        31.0               1.2   141.0        3.5
397                 100.0        26.0               0.6   137.0        4.4
398                 114.0        50.0               1.0   135.0        4.9
399                 131.0        18.0               1.1   141.0        3.5

     Haemoglobin  Packed Cell Volume  White Blood Cell Count  \
0           15.4                44.0                  7800.0
1           11.3                38.0                  6000.0
2            9.6                31.0                  7500.0
3           11.2                32.0                  6700.0
4           11.6                35.0                  7300.0
..           ...                 ...                     ...
395         15.7                47.0                  6700.0
396         16.5                54.0                  7800.0
397         15.8                49.0                  6600.0
398         14.2                51.0                  7200.0
399         15.8                53.0                  6800.0

     Red blood cell count
0                     5.2
1                     6.5
2                     3.4
3                     3.9
4                     4.6
..                    ...
395                   4.9
396                   6.2
397                   5.4
398                   5.9
399                   6.1

[400 rows x 14 columns]


Imputed values with 2 neighbors:
      age  Blood Pressure  Specific Gravity  Albumin  Sugar  \
0    48.0            80.0             1.020      1.0    0.0
1     7.0            50.0             1.020      4.0    0.0
2    62.0            80.0             1.010      2.0    3.0
3    48.0            70.0             1.005      4.0    0.0
4    51.0            80.0             1.010      2.0    0.0
..    ...             ...               ...      ...    ...
395  55.0            80.0             1.020      0.0    0.0
396  42.0            70.0             1.025      0.0    0.0
397  12.0            80.0             1.020      0.0    0.0
398  17.0            60.0             1.025      0.0    0.0
399  58.0            80.0             1.025      0.0    0.0

     Blood Glucose random  Blood Urea  Serum Creatinine  Sodium  Potassium  \
0                   121.0        36.0               1.2   139.0       4.45
1                   101.5        18.0               0.8   138.0       3.80
2                   423.0        53.0               1.8   132.0       4.05
3                   117.0        56.0               3.8   111.0       2.50
4                   106.0        26.0               1.4   137.0       4.30
..                    ...         ...               ...     ...        ...
395                 140.0        49.0               0.5   150.0       4.90
396                  75.0        31.0               1.2   141.0       3.50
397                 100.0        26.0               0.6   137.0       4.40
398                 114.0        50.0               1.0   135.0       4.90
399                 131.0        18.0               1.1   141.0       3.50

     Haemoglobin  Packed Cell Volume  White Blood Cell Count  \
0           15.4                44.0                  7800.0
1           11.3                38.0                  6000.0
2            9.6                31.0                  7500.0
3           11.2                32.0                  6700.0
4           11.6                35.0                  7300.0
..           ...                 ...                     ...
395         15.7                47.0                  6700.0
396         16.5                54.0                  7800.0
397         15.8                49.0                  6600.0
398         14.2                51.0                  7200.0
399         15.8                53.0                  6800.0

     Red blood cell count
0                     5.2
1                     5.5
2                     3.2
3                     3.9
4                     4.6
..                    ...
395                   4.9
396                   6.2
397                   5.4
398                   5.9
399                   6.1

[400 rows x 14 columns]


Imputed values with 3 neighbors:
      age  Blood Pressure  Specific Gravity  Albumin  Sugar  \
0    48.0            80.0             1.020      1.0    0.0
1     7.0            50.0             1.020      4.0    0.0
2    62.0            80.0             1.010      2.0    3.0
3    48.0            70.0             1.005      4.0    0.0
4    51.0            80.0             1.010      2.0    0.0
..    ...             ...               ...      ...    ...
395  55.0            80.0             1.020      0.0    0.0
396  42.0            70.0             1.025      0.0    0.0
397  12.0            80.0             1.020      0.0    0.0
398  17.0            60.0             1.025      0.0    0.0
399  58.0            80.0             1.025      0.0    0.0

     Blood Glucose random  Blood Urea  Serum Creatinine  Sodium  Potassium  \
0              121.000000        36.0               1.2   139.0   4.533333
1              113.666667        18.0               0.8   137.0   4.000000
2              423.000000        53.0               1.8   132.0   4.666667
3              117.000000        56.0               3.8   111.0   2.500000
4              106.000000        26.0               1.4   138.0   4.233333
..                    ...         ...               ...     ...        ...
395            140.000000        49.0               0.5   150.0   4.900000
396             75.000000        31.0               1.2   141.0   3.500000
397            100.000000        26.0               0.6   137.0   4.400000
398            114.000000        50.0               1.0   135.0   4.900000
399            131.000000        18.0               1.1   141.0   3.500000

     Haemoglobin  Packed Cell Volume  White Blood Cell Count  \
0           15.4                44.0                  7800.0
1           11.3                38.0                  6000.0
2            9.6                31.0                  7500.0
3           11.2                32.0                  6700.0
4           11.6                35.0                  7300.0
..           ...                 ...                     ...
395         15.7                47.0                  6700.0
396         16.5                54.0                  7800.0
397         15.8                49.0                  6600.0
398         14.2                51.0                  7200.0
399         15.8                53.0                  6800.0

     Red blood cell count
0                5.200000
1                5.400000
2                3.966667
3                3.900000
4                4.600000
..                    ...
395              4.900000
396              6.200000
397              5.400000
398              5.900000
399              6.100000

[400 rows x 14 columns]


Imputed values with 4 neighbors:
      age  Blood Pressure  Specific Gravity  Albumin  Sugar  \
0    48.0            80.0             1.020      1.0    0.0
1     7.0            50.0             1.020      4.0    0.0
2    62.0            80.0             1.010      2.0    3.0
3    48.0            70.0             1.005      4.0    0.0
4    51.0            80.0             1.010      2.0    0.0
..    ...             ...               ...      ...    ...
395  55.0            80.0             1.020      0.0    0.0
396  42.0            70.0             1.025      0.0    0.0
397  12.0            80.0             1.020      0.0    0.0
398  17.0            60.0             1.025      0.0    0.0
399  58.0            80.0             1.025      0.0    0.0

     Blood Glucose random  Blood Urea  Serum Creatinine  Sodium  Potassium  \
0                   121.0        36.0               1.2  138.50       4.35
1                   112.0        18.0               0.8  136.50       3.95
2                   423.0        53.0               1.8  132.75       4.45
3                   117.0        56.0               3.8  111.00       2.50
4                   106.0        26.0               1.4  140.25       4.05
..                    ...         ...               ...     ...        ...
395                 140.0        49.0               0.5  150.00       4.90
396                  75.0        31.0               1.2  141.00       3.50
397                 100.0        26.0               0.6  137.00       4.40
398                 114.0        50.0               1.0  135.00       4.90
399                 131.0        18.0               1.1  141.00       3.50

     Haemoglobin  Packed Cell Volume  White Blood Cell Count  \
0           15.4                44.0                  7800.0
1           11.3                38.0                  6000.0
2            9.6                31.0                  7500.0
3           11.2                32.0                  6700.0
4           11.6                35.0                  7300.0
..           ...                 ...                     ...
395         15.7                47.0                  6700.0
396         16.5                54.0                  7800.0
397         15.8                49.0                  6600.0
398         14.2                51.0                  7200.0
399         15.8                53.0                  6800.0

     Red blood cell count
0                     5.2
1                     4.8
2                     3.9
3                     3.9
4                     4.6
..                    ...
395                   4.9
396                   6.2
397                   5.4
398                   5.9
399                   6.1

[400 rows x 14 columns]